gods:
  Illubatar:
    potionEffect:
      type: "ABSORPTION"
      duration: 500
      intensity: 2
    material: "DIAMOND"
    block: "DIAMOND_BLOCK"
  Villios:
    potionEffect:
      type: "HERO_OF_THE_VILLAGE"
      duration: 500
      intensity: 2
    material: "DIAMOND"
    block: "DIAMOND_BLOCK"
  Luckio:
    potionEffect:
      type: "LUCK"
      duration: 300
      intensity: 2
    material: "DIAMOND"
    block: "DIAMOND_BLOCK"
  Costilia:
    potionEffect:
      type: "WATER_BREATHING"
      duration: 500
      intensity: 4
    material: "DIAMOND"
    block: "DIAMOND_BLOCK"
  Jumilo:
    potionEffect:
      type: "JUMP"
      duration: 300
      intensity: 2
    material: "DIAMOND"
    block: "DIAMOND_BLOCK"
  Warlium:
    potionEffect:
      type: "INCREASE_DAMAGE"
      duration: 300
      intensity: 2
    material: "DIAMOND"
    block: "DIAMOND_BLOCK"